#!/usr/bin/env python3
import json
import sys
import os

summary_md = ""
try:
    with open('ai-quality-report.json') as f:
        report = json.load(f)
    stats = report.get("statistics", {})
    summary = report.get("summary", {})
    summary_md += "### Scan Overview\n"
    summary_md += f"- **Files scanned:** {summary.get('files_scanned', stats.get('files_with_issues', 0))}\n"
    summary_md += f"- **Total lines:** {stats.get('total_lines', 'N/A')}\n"
    summary_md += f"- **Functions with docstrings:** {stats.get('functions_with_docstrings', 0)}\n\n"
    summary_md += "### Issues by Severity\n"
    for severity in ["Critical", "High", "Medium", "Low", "Info"]:
        count = summary.get("by_severity", {}).get(severity, 0)
        if count > 0:
            emoji = "🔴" if severity in ["Critical", "High"] else "🟡" if severity == "Medium" else "🟢"
            summary_md += f"- {emoji} **{severity}:** {count}\n"
    summary_md += "\n### Issues by Category\n"
    categories = report.get("by_category", {})
    for category, count in categories.items():
        if count > 0:
            emoji = {"security":"🔒","bug":"🐛","quality":"📐","style":"💅","type":"🏷️","formatting":"✨"}.get(category, "•")
            summary_md += f"- {emoji} **{category}:** {count}\n"
    if summary.get("has_blocking_issues"):
        summary_md += "\n⚠️ **Blocking Issues Detected** (Critical/High severity or Medium+ security)\n"
    else:
        summary_md += "\n✅ **No blocking issues found**\n"
except FileNotFoundError:
    summary_md += "⚠️ Quality report not found\n"
except Exception as e:
    summary_md += f"⚠️ Error reading report: {e}\n"
summary_md += "\n---\n*Generated by AI Code Quality Scanner*\n"
print(summary_md, end='')

summary_file = os.getenv('GITHUB_STEP_SUMMARY')
if summary_file:
    try:
        with open(summary_file, 'a') as f:
            f.write(summary_md)
    except Exception as e:
        print(f"Failed to write to step summary: {e}", file=sys.stderr)
